language: node_js
node_js:
  - '12.13.0'
os:
  - linux
dist: trusty
before_install:
  - npm install -g yarn@1.22.0
install:
  - yarn install --frozen-lockfile
script:
  - yarn generate
  - yarn lint
  - yarn lint-deps
  - yarn prepare-beta-build
  - yarn build
  - ./travis.sh
env:
  global:
    - SIGNAL_ENV: production
sudo: false
notifications:
  email: false
