platform:
  - x64

cache:
  - '%LOCALAPPDATA%\electron\Cache'
  - node_modules -> package.json

install:
  - systeminfo | findstr /C:"OS"
  - set PATH=C:\Ruby23-x64\bin;%PATH%
  - ps: Install-Product node 12.13.0 x64
  - npm install -g yarn@1.22.0
  - yarn install --frozen-lockfile

build_script:
  - yarn generate
  - yarn lint-windows
  - yarn lint-deps
  - node build\grunt.js
  - yarn test-node
  - type package.json | findstr /v certificateSubjectName > temp.json
  - move temp.json package.json
  - type package.json | findstr /v certificateSha1 > temp.json
  - move temp.json package.json
  - yarn prepare-beta-build
  - yarn build

test_script:
  - node build\grunt.js test
  - set NODE_ENV=production
  - node build\grunt.js test-release:win

environment:
  SIGNAL_ENV: production
